# Generated by Django 3.1.4 on 2021-01-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rues_france', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranceRues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=100)),
                ('code_post', models.IntegerField()),
                ('nom_comm', models.CharField(max_length=100)),
            ],
        ),
    ]
