# Generated by Django 3.1.4 on 2021-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rues_france', '0002_francerues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneDepartementRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune_INSEE', models.CharField(blank=True, max_length=6)),
                ('nom_commune_postal', models.CharField(blank=True, max_length=50)),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('libelle_acheminement', models.CharField(blank=True, max_length=50)),
                ('ligne_5', models.CharField(blank=True, max_length=40)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('code_commune', models.IntegerField(blank=True, null=True)),
                ('article', models.CharField(blank=True, max_length=5)),
                ('nom_commune', models.CharField(blank=True, max_length=50)),
                ('nom_commune_complet', models.CharField(blank=True, max_length=50)),
                ('code_departement', models.CharField(blank=True, max_length=3)),
                ('nom_departement', models.CharField(blank=True, max_length=30)),
                ('code_region', models.IntegerField(blank=True, null=True)),
                ('nom_region', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
